/*
 * MB_Addresses.h
 *
 *  Created on: May 12, 2022
 *      Author: RASEL_EEE
 */

#ifndef INC_MB_ADDRESSES_H_
#define INC_MB_ADDRESSES_H_



/* Coils addresses
 * FC: 02 read discrete inputs
*/
typedef enum MB_DIAddrEnum{
	/*Digital outputs------------*/
	//@NB: never change this addressing for the digital inputs, MB read function use this sequence
	MB_DIA_DI1_STATUS = 10001U,
	MB_DIA_DI2_STATUS,	//
	MB_DIA_DI3_STATUS,	//
	MB_DIA_DI4_STATUS,	//
	MB_DIA_DI5_STATUS,	//
	MB_DIA_DI6_STATUS,	//
	MB_DIA_DI7_STATUS,	//
	MB_DIA_DI8_STATUS,	//
	MB_DIA_MAX,
}MB_DIAddrEnum;



// Coils addresses write coil: FC-05, readCOil: 01
typedef enum MB_CoilAddrEnum{
	/*Digital outputs------------*/
	//@NB: never change this addressing for the digital inputs, MB read function use this sequence
	MB_COA_DO1_ENABLE = 1U,	//
	MB_COA_DO2_ENABLE,	//
	MB_COA_DO3_ENABLE,	//
	MB_COA_DO4_ENABLE,	//
	MB_COA_DO5_ENABLE,	//
	MB_COA_DO6_ENABLE,	//
//	MB_COA_DO7_ENABLE,	//
//	MB_COA_DO8_ENABLE,	//


	/*Analog outputs------------*/
	//@NB: never change this addressing for the digital inputs, MB read function use this sequence
	MB_COA_AO1_ENABLE = 17,	//
	MB_COA_AO2_ENABLE,	//
	MB_COA_AO3_ENABLE,	//
	MB_COA_AO4_ENABLE,	//

	/*Dev net info ------------*/
	MB_COA_MB_SAVE_NET_INFO = 29,	//

	/*NModbus RTU Serial------------*/
	MB_COA_MB_SAVE_SERIAL_CONFIG = 33,	//

	/*NModbus RTU Master------------*/
	MB_COA_MB_MSTR_ENABLE = 36,	//

	/*NModbus RTU Slave------------*/
	MB_COA_MB_SAVE_SLAVE_ADDR = 39,	//

	/*Modbus TCP Server--------------*/
//	MB_COA_MB_TCPS_RELOAD = 41,

	/*Modbus TCP Client--------------*/
	MB_COA_MB_TCPC_SOCK_CONN_DISCONN = 46,	//

	/*Encoder--------------------*/
	MB_COA_ENC_ENABLE = 51,



	/*Dev utilities--------------*/
	MB_COA_RESTART = 61,
	MB_COA_DBUG_ENABLE,
	MB_COA_MAX,
}MB_CoilAddrEnum;




// Input register addresses
typedef enum MB_IRAddrEnum{
	MB_IRA_AI1_VALUE_12BIT  = 30001U,	//
	MB_IRA_AI1_CURRENT,	//
	MB_IRA_AI1_VOLTAGE,	//

	MB_IRA_AI2_VALUE_12BIT = 30006,	//
	MB_IRA_AI2_CURRENT,	//
	MB_IRA_AI2_VOLTAGE,	//

	MB_IRA_AI3_VALUE_12BIT = 30011,	//
	MB_IRA_AI3_CURRENT,	//
	MB_IRA_AI3_VOLTAGE,	//

	MB_IRA_AI4_VALUE_12BIT = 30016,	//
	MB_IRA_AI4_CURRENT,	//
	MB_IRA_AI4_VOLTAGE,	//


	/*NModbus TCP Server------------*/

	//Socket 1
	MB_IRA_MB_TCPS_SOCK0_DEST_IP_1  = 30021,	//
	MB_IRA_MB_TCPS_SOCK0_DEST_IP_2,	//
	MB_IRA_MB_TCPS_SOCK0_DEST_IP_3,	//
	MB_IRA_MB_TCPS_SOCK0_DEST_IP_4,	//
	MB_IRA_MB_TCPS_SOCK0_DEST_PORT,	//
	MB_IRA_MB_TCPS_SOCK0_STATUS,	//

	//Socket 2
	MB_IRA_MB_TCPS_SOCK1_DEST_IP_1 = 30036,
	MB_IRA_MB_TCPS_SOCK1_DEST_IP_2,
	MB_IRA_MB_TCPS_SOCK1_DEST_IP_3,
	MB_IRA_MB_TCPS_SOCK1_DEST_IP_4,
	MB_IRA_MB_TCPS_SOCK1_DEST_PORT,
	MB_IRA_MB_TCPS_SOCK1_STATUS,

	/*NModbus TCP client------------*/
	MB_IRA_MB_TCPC_SOCK_SRC_PORT = 30051,	//
	MB_IRA_MB_TCPC_SOCK_STATUS ,	//

	/*Digital Inputs------------*/
	MB_IRA_DI1_SIGNAL_PERIOD = 30061,
	MB_IRA_DI2_SIGNAL_PERIOD = 30066,

	/*Encoder-------------------*/
	MB_IRA_ENC_QUAD_DIRECTION = 30071,
	MB_IRA_ENC_QUAD_COUNT_LSB16,
	MB_IRA_ENC_QUAD_COUNT_MSB16,
	MB_IRA_ENC_INCR_CHA_COUNT_LSB16,
	MB_IRA_ENC_INCR_CHA_COUNT_MSB16,
	MB_IRA_ENC_INCR_CHB_COUNT_LSB16,
	MB_IRA_ENC_INCR_CHB_COUNT_MSB16,



	/*Utilities----------------*/
	MB_IRA_DEV_HW_VERSION = 30101,
	MB_IRA_DEV_FW_VERSION,

	/*PID-------------------*/
	MB_IRA_PID1_FEEDBACK = 30111,
	MB_IRA_PID1_OUTPUT,
	MB_IRA_PID2_FEEDBACK = 30116,
	MB_IRA_PID2_OUTPUT,

	/*Diagnosis---------------------*/
	//RTU bus error
	MB_IRA_DIAG_RTU_OVERRUN_ERR_COUNT = 30151,
	MB_IRA_DIAG_RTU_PARITY_ERR_COUNT,
	MB_IRA_DIAG_RTU_NOISE_ERR_COUNT,
	MB_IRA_DIAG_RTU_FRAME_ERR_COUNT,
	MB_IRA_DIAG_RTU_DMATX_ERR_COUNT,
	MB_IRA_DIAG_RTU_DMATX_ERR_CODE,
	MB_IRA_DIAG_RTU_DMARX_ERR_CODE,

	//SPI bus error
	MB_IRA_DIAG_SPI_OVERRUN_ERR_COUNT = 30161,
	MB_IRA_DIAG_SPI_MODF_ERR_COUNT,
	MB_IRA_DIAG_SPI_CRC_ERR_COUNT,
	MB_IRA_DIAG_SPI_FRAME_ERR_COUNT,
	MB_IRA_DIAG_SPI_DMATX_ERR_COUNT,
	MB_IRA_DIAG_SPI_FLAG_ERR_COUNT,
	MB_IRA_DIAG_SPI_ABORT_ERR_COUNT,
	MB_IRA_DIAG_SPI_DMATX_ERR_CODE,
	MB_IRA_DIAG_SPI_DMARX_ERR_CODE,

	//I2C comm. err
	MB_IRA_DIAG_I2C_ERR_CODE = 30176,
	MB_IRA_DIAG_I2C_DMATX_CODE,
	MB_IRA_DIAG_I2C_DMARX_CODE,

	MB_IRA_MAX,
}MB_IRAddrEnum;



// Holding register addresses
typedef enum MB_HRAddrEnum{

	/*Digital Inputs--------------*/
	MB_HRA_DI1_MODE = 40001U,
	MB_HRA_DI1_COUNTER_TYPE,		// note used right now
	MB_HRA_DI1_COUNTER_MODE,		// note used right now
	MB_HRA_DI1_TRIGGER_MODE,		// note used right now
	MB_HRA_DI1_DEBOUNCE_MAX,
	MB_HRA_DI1_SIGNAL_PERIOD_MIN = 40010,

	MB_HRA_DI2_MODE = 40011U,
	MB_HRA_DI2_COUNTER_TYPE,
	MB_HRA_DI2_COUNTER_MODE,
	MB_HRA_DI2_TRIGGER_MODE,
	MB_HRA_DI2_DEBOUNCE_MAX,
	MB_HRA_DI2_SIGNAL_PERIOD_MIN = 40020,

	MB_HRA_DI3_MODE = 40021U,
	MB_HRA_DI3_COUNTER_TYPE,
	MB_HRA_DI3_COUNTER_MODE,
	MB_HRA_DI3_TRIGGER_MODE,
	MB_HRA_DI3_DEBOUNCE_MAX,

	MB_HRA_DI4_MODE = 40031U,
	MB_HRA_DI4_COUNTER_TYPE,
	MB_HRA_DI4_COUNTER_MODE,
	MB_HRA_DI4_TRIGGER_MODE,
	MB_HRA_DI4_DEBOUNCE_MAX,

	MB_HRA_DI5_MODE = 40041U,
	MB_HRA_DI5_COUNTER_TYPE,
	MB_HRA_DI5_COUNTER_MODE,
	MB_HRA_DI5_TRIGGER_MODE,
	MB_HRA_DI5_DEBOUNCE_MAX,

	MB_HRA_DI6_MODE = 40051U,
	MB_HRA_DI6_COUNTER_TYPE,
	MB_HRA_DI6_COUNTER_MODE,
	MB_HRA_DI6_TRIGGER_MODE,
	MB_HRA_DI6_DEBOUNCE_MAX,

	MB_HRA_DI7_MODE = 40061U,
	MB_HRA_DI7_COUNTER_TYPE,
	MB_HRA_DI7_COUNTER_MODE,
	MB_HRA_DI7_TRIGGER_MODE,
	MB_HRA_DI7_DEBOUNCE_MAX,

	MB_HRA_DI8_MODE = 40071U,
	MB_HRA_DI8_COUNTER_TYPE,
	MB_HRA_DI8_COUNTER_MODE,
	MB_HRA_DI8_TRIGGER_MODE,
	MB_HRA_DI8_DEBOUNCE_MAX,


	/*Digital Outputs--------------*/
	MB_HRA_DO_HSPWM_FREQ = 40081,

	MB_HRA_DO1_SRC = 40086,
	MB_HRA_DO1_MODE,
//	MB_HRA_DO1_PWM_DUTY,

	MB_HRA_DO2_SRC = 40091,
	MB_HRA_DO2_MODE,
//	MB_HRA_DO2_PWM_DUTY,

	MB_HRA_DO3_SRC = 40096,
	MB_HRA_DO3_MODE,
//	MB_HRA_DO3_PWM_DUTY,


	MB_HRA_DO4_SRC = 40101,
	MB_HRA_DO4_MODE,
//	MB_HRA_DO4_PWM_DUTY,

	MB_HRA_DO5_SRC= 40106,
	MB_HRA_DO5_MODE,
	MB_HRA_DO5_PWM_DUTY,

	MB_HRA_DO6_SRC= 40114,
	MB_HRA_DO6_MODE,
	MB_HRA_DO6_PWM_DUTY,

//	MB_HRA_DO7_SRC= 40122,
//	MB_HRA_DO7_MODE,
//	MB_HRA_DO7_PWM_DUTY,
//
//	MB_HRA_DO8_SRC= 40130,
//	MB_HRA_DO8_MODE,
//	MB_HRA_DO8_PWM_DUTY,

	/*Analog Inputs-----------*/
	MB_HRA_AI1_MODE = 40138,	//
	MB_HRA_AI2_MODE,	//
	MB_HRA_AI3_MODE,	//
	MB_HRA_AI4_MODE,	//

	/*Analog outputs------------*/
	MB_HRA_AO1_MODE= 40146,	//
	MB_HRA_AO1_DUTY,	//
	MB_HRA_AO1_SRC,


	MB_HRA_AO2_MODE = 40151,//
	MB_HRA_AO2_DUTY,	//
	MB_HRA_AO2_SRC,


	MB_HRA_AO3_MODE = 40156,	//
	MB_HRA_AO3_DUTY,	//
	MB_HRA_AO3_SRC,


	MB_HRA_AO4_MODE = 40161,	//
	MB_HRA_AO4_DUTY,	//
	MB_HRA_AO4_SRC,


	/*Net Information------------*/


	MB_HRA_DEV_MAC_1 = 40171,		//ok
	MB_HRA_DEV_MAC_2,	//
	MB_HRA_DEV_MAC_3,	//
	MB_HRA_DEV_MAC_4,	//
	MB_HRA_DEV_MAC_5,	//
	MB_HRA_DEV_MAC_6,	//

	MB_HRA_DEV_IP_1,	//
	MB_HRA_DEV_IP_2,	//
	MB_HRA_DEV_IP_3,	//
	MB_HRA_DEV_IP_4,	//

	MB_HRA_DEV_SN_1,	//
	MB_HRA_DEV_SN_2,	//
	MB_HRA_DEV_SN_3,	//
	MB_HRA_DEV_SN_4,	//

	MB_HRA_DEV_GW_1,	//
	MB_HRA_DEV_GW_2,	//
	MB_HRA_DEV_GW_3,	//
	MB_HRA_DEV_GW_4,	//

	MB_HRA_DEV_DNS_1,	//
	MB_HRA_DEV_DNS_2,	//
	MB_HRA_DEV_DNS_3,	//
	MB_HRA_DEV_DNS_4,	//


	/*NModbus TCP Server------------*/
//	MB_HRA_MB_TCPS_TRANS_MAX,
	//socket - 0 & 1
	MB_HRA_MB_TCPS_SOCK0_SRC_PORT  = 40201,	//
	MB_HRA_MB_TCPS_SOCK0_KPALV_TIM,	//

//	MB_HRA_MB_TCPS_SOCK1_SRC_PORT = 40211,
//	MB_HRA_MB_TCPS_SOCK1_KPALV_TIM,

	/*NModbus TCP Client------------*/
	MB_HRA_MB_TCPC_DEST_IP_1 = 40221,	//
	MB_HRA_MB_TCPC_DEST_IP_2,	//
	MB_HRA_MB_TCPC_DEST_IP_3,	//
	MB_HRA_MB_TCPC_DEST_IP_4,	//
	MB_HRA_MB_TCPC_DEST_PORT,	//
	MB_HRA_MB_TCPC_SOCK_KPALV_TIM,	//
	MB_HRA_MB_TCPC_TX_TIM_INTRVAL,
	MB_HRA_MB_TCPC_SOCK_CONN_MODE,	//TODO: to remove


	/*NModbus RTU Serial------------*/
	MB_HRA_MB_SERIAL_CONFIG = 40241,			//
	MB_HRA_MB_SERIAL_BAUD_RATE_LS16B,
	MB_HRA_MB_SERIAL_BAUD_RATE_MS16B,
	MB_HRA_MB_SERIAl_PROTOCOL,



	/*NModbus RTU Master------------*/
	MB_HRA_MB_MSTR_SLAVE_START_ADDR = 40251,	//
	MB_HRA_MB_MSTR_NUM_OF_SLAVES,	//
	MB_HRA_MB_MSTR_REPLY_TIMEOUT,	//
	MB_HRA_MB_MSTR_PERIODIC_REQ_INTERVAL,	//
//	MB_HRA_MB_MSTR_RETRY_MAX,

	/*NModbus RTU Slave------------*/
	MB_HRA_MB_SLAVE_ADDRESS = 40261,	//
	MB_HRA_MB_SLAVE_CUST_RESP_TIMEOUT,	//

	/*NModbus Gateway------------*/
	MB_HRA_MB_GW_TIMEOUT =  40266,	//
//	MB_HRA_MB_GW_MODE,

	/*Utilities----------------*/
	MB_HRA_DEV_MODE = 40281,


	/*Encoder----------------*/
	MB_HRA_ENC_MODE = 40291,
	MB_HRA_ENC_QUAD_TRIG_MODE,
	MB_HRA_ENC_CHA_TRIG_MODE,
	MB_HRA_ENC_CHB_TRIG_MODE,
	MB_HRA_ENC_CHZ_TRIG_MODE,

	/*PID-------------------*/
//	MB_HRA_PID1_OUTPUT_MODE = 40301,
	MB_HRA_PID1_KP = 40301,
	MB_HRA_PID1_KI,
	MB_HRA_PID1_KD,
	MB_HRA_PID1_I_OUT_LIMIT,
//	MB_HRA_PID1_FB_SOURCE,
//	MB_HRA_PID1_HYSTERESIS_VALUE,
//	MB_HRA_PID1_SETPOINT,

//	MB_HRA_PID2_OUTPUT_MODE = 40311,
	MB_HRA_PID2_KP = 40311,
	MB_HRA_PID2_KI,
	MB_HRA_PID2_KD,
	MB_HRA_PID2_I_OUT_LIMIT,
//	MB_HRA_PID2_FB_SOURCE,
//	MB_HRA_PID2_HYSTERESIS_VALUE,
//	MB_HRA_PID2_SETPOINT,

	MB_HRA_MAX,
}MB_HRAddrEnum;


#endif /* INC_MB_ADDRESSES_H_ */
