/*
 * Flash_Address.h
 *
 *  Created on: May 25, 2022
 *      Author: RASEL_EEE
 */

#ifndef INC_FLASH_ADDRESS_H_
#define INC_FLASH_ADDRESS_H_


typedef enum Storage_Address{
	SA_MEM_FIRST_RUN_CHECK = 0,


	/*Analog Inputs-----------*/
	SA_AI1_MODE,
	SA_AI2_MODE,
	SA_AI3_MODE,
	SA_AI4_MODE,


	/*Analog outputs 1 to 4----------*/
	SA_AO1_MODE,
//	SA_AO1_SRC,
	SA_AO1_DUTY,

	SA_AO2_MODE,
//	SA_AO2_SRC,
	SA_AO2_DUTY,

	SA_AO3_MODE,
//	SA_AO3_SRC,
	SA_AO3_DUTY,

	SA_AO4_MODE,
//	SA_AO4_SRC,
	SA_AO4_DUTY,

	/*Net Information------------*/
	SA_DEV_MAC_1,
	SA_DEV_MAC_2,
	SA_DEV_MAC_3,
	SA_DEV_MAC_4,
	SA_DEV_MAC_5,
	SA_DEV_MAC_6,

	SA_DEV_IP_1,
	SA_DEV_IP_2,
	SA_DEV_IP_3,
	SA_DEV_IP_4,

	SA_DEV_SN_1,
	SA_DEV_SN_2,
	SA_DEV_SN_3,
	SA_DEV_SN_4,

	SA_DEV_GW_1,
	SA_DEV_GW_2,
	SA_DEV_GW_3,
	SA_DEV_GW_4,

	SA_DEV_DNS_1,
	SA_DEV_DNS_2,
	SA_DEV_DNS_3,
	SA_DEV_DNS_4,


	/*NModbus TCP Server------------*/
	//socket - 1 & 2
	SA_MB_TCPS_SOCK0_SRC_PORT,
	SA_MB_TCPS_SOCK0_KPALV_TIM,

	SA_MB_TCPS_SOCK1_KPALV_TIM,
	SA_MB_TCPS_SOCK1_SRC_PORT,

	/*NModbus TCP client------------*/
	SA_MB_TCPC_DEST_IP_1,
	SA_MB_TCPC_DEST_IP_2,
	SA_MB_TCPC_DEST_IP_3,
	SA_MB_TCPC_DEST_IP_4,
	SA_MB_TCPC_DEST_PORT,
	SA_MB_TCPC_SOCK_KPALV_TIM,
	SA_MB_TCPC_SOCK_CONN_MODE,
	SA_MB_TCPC_TX_TIM_INTRVAL,

	/*NModbus RTU Serial------------*/
	SA_MB_SERIAL_CONFIG,
	SA_MB_SERIAl_BAUD_RATE_USER_DEF,
	SA_MB_SERIAl_PROTOCOL,

	/*Modbus Master---------------*/
	SA_MB_MSTR_ENABLE,
	SA_MB_MSTR_SLV_START_ADDR,
	SA_MB_MSTR_NUM_OF_SLAVE,
	SA_MB_MSTR_REPLY_TIMEOUT,
	SA_MB_MSTR_PERIODIC_REQ_INTERVAL,

	/*Modbus slaves---------------*/
	SA_SLAVE_ADDRESS,


	/*NModbus Gateway------------*/
	SA_MB_GW_TIMEOUT,

	/*Utilities----------------*/
	SA_DEV_MODE,


	/*Analog output-----------*/
	SA_AO1_ENABLE,
	SA_AO2_ENABLE,
	SA_AO3_ENABLE,
	SA_AO4_ENABLE,

	/*Modbus slaves---------------*/
	SA_MB_SLAVE_CUST_RESP_TIMEOUT,

	/*Analog outputs 1 to 4----------*/
	SA_AO1_SRC,
	SA_AO2_SRC,
	SA_AO3_SRC,
	SA_AO4_SRC,

	/*Digital Inputs--------------*/
	SA_DI1_MODE,
	SA_DI1_COUNTER_TYPE,
	SA_DI1_COUNTER_MODE,
	SA_DI1_TRIGGER_MODE,
	SA_DI1_DEBOUNCE_MAX,
	SA_DI1_SIGNAL_PERIOD_MIN,

	SA_DI2_MODE,
	SA_DI2_COUNTER_TYPE,
	SA_DI2_COUNTER_MODE,
	SA_DI2_TRIGGER_MODE,
	SA_DI2_DEBOUNCE_MAX,
	SA_DI2_SIGNAL_PERIOD_MIN,

	SA_DI3_MODE,
	SA_DI3_COUNTER_TYPE,
	SA_DI3_COUNTER_MODE,
	SA_DI3_TRIGGER_MODE,
	SA_DI3_DEBOUNCE_MAX,

	SA_DI4_MODE,
	SA_DI4_COUNTER_TYPE,
	SA_DI4_COUNTER_MODE,
	SA_DI4_TRIGGER_MODE,
	SA_DI4_DEBOUNCE_MAX,

	SA_DI5_MODE,
	SA_DI5_COUNTER_TYPE,
	SA_DI5_COUNTER_MODE,
	SA_DI5_TRIGGER_MODE,
	SA_DI5_DEBOUNCE_MAX,

	SA_DI6_MODE,
	SA_DI6_COUNTER_TYPE,
	SA_DI6_COUNTER_MODE,
	SA_DI6_TRIGGER_MODE,
	SA_DI6_DEBOUNCE_MAX,

	SA_DI7_MODE,
	SA_DI7_COUNTER_TYPE,
	SA_DI7_COUNTER_MODE,
	SA_DI7_TRIGGER_MODE,
	SA_DI7_DEBOUNCE_MAX,

	SA_DI8_MODE,
	SA_DI8_COUNTER_TYPE,
	SA_DI8_COUNTER_MODE,
	SA_DI8_TRIGGER_MODE,
	SA_DI8_DEBOUNCE_MAX,


	/*Digital Outputs--------------*/
	SA_DO_HSPWM_FREQ,

	SA_DO1_SRC,
	SA_DO1_MODE,
//	SA_DO1_PWM_DUTY,

	SA_DO2_SRC,
	SA_DO2_MODE,
//	SA_DO2_PWM_DUTY,

	SA_DO3_SRC,
	SA_DO3_MODE,
//	SA_DO3_PWM_DUTY,


	SA_DO4_SRC,
	SA_DO4_MODE,
//	SA_DO4_PWM_DUTY,

	SA_DO5_SRC,
	SA_DO5_MODE,
	SA_DO5_PWM_DUTY,

	SA_DO6_SRC,
	SA_DO6_MODE,
	SA_DO6_PWM_DUTY,

	SA_DO7_SRC,
	SA_DO7_MODE,
	SA_DO7_PWM_DUTY,

	SA_DO8_SRC,
	SA_DO8_MODE,
	SA_DO8_PWM_DUTY,

	/*PID-------------*/
//	SA_PID1_OUTPUT_MODE,
	SA_PID1_KP,
	SA_PID1_KI,
	SA_PID1_KD,
	SA_PID1_I_OUT_LIMIT,
//	SA_PID1_FB_SOURCE,
//	SA_PID1_HYSTERESIS_VALUE,
//	SA_PID1_SETPOINT,

//	SA_PID2_OUTPUT_MODE,
	SA_PID2_KP,
	SA_PID2_KI,
	SA_PID2_KD,
	SA_PID2_I_OUT_LIMIT,
//	SA_PID2_FB_SOURCE,
//	SA_PID2_HYSTERESIS_VALUE,
//	SA_PID2_SETPOINT,

	/*Encoder------------*/
	SA_ENC_ENABLE,
	SA_ENC_MODE,
	SA_ENC_QUAD_TRIG_MODE,
	SA_ENC_CHA_TRIG_MODE,
	SA_ENC_CHB_TRIG_MODE,
	SA_ENC_CHZ_TRIG_MODE,

	SA_DBUG_ENABLE,
	SA_MB_LISTEN_ONLY_MODE,
	SA_MAX,							//
}Storage_Address;

#endif /* INC_FLASH_ADDRESS_H_ */
