/*
 * Strings.h
 *
 *  Created on: Oct 14, 2022
 *      Author: wsrra
 */

#ifndef INC_STRINGS_H_
#define INC_STRINGS_H_

#define STR_SOCKET		 				"Socket"
#define STR_INVALID		 				"Invalid"
#define STR_NUMBER		 				"Number"
#define STR_NOT			 				"Not"
#define STR_SUPPORT		 				"Support"
#define STR_MODE		 				"Mode"
#define STR_FLAG		 				"Flag"
#define STR_ERROR		 				"Error"
#define STR_OPENED		 				"Opened"
#define STR_OPENING		 				"Opening"
#define STR_LISTENING 					"Listening"
#define STR_CONNECTING	 				"Connecting"
#define STR_CONNECTED 					"Connected"
#define STR_SENDING		 				"Sending"
#define STR_SENT		 				"Sent"
#define STR_RECEIVING		 			"Receiving"
#define STR_RECEIVED		 			"Received"
#define STR_DISCONNECTING		 		"Disconnecting"
#define STR_DISCONNECTED 				"Disconnected"
#define STR_SUCCESS		 				"Success"
#define STR_FAILED		 				"Failed"
#define STR_CLOSED		 				"Closed"
#define STR_CLOSING		 				"Closing"
#define STR_IS		 					"Is"
#define STR_INITIALIZED 				"Initialized"
#define STR_UNEXPECTEDLY 				"Unexpectedly"
#define STR_TO		 					"To"
#define STR_OR		 					"Or"
#define STR_AT		 					"At"
#define STR_SERVER						"Server"
#define STR_CLIENT						"Client"
#define STR_NET		 					"Net"
#define STR_INFO						"Info"
#define STR_CONFIGURED 					"Configured"
#define STR_STATUS 						"Status"
#define STR_FOR 						"For"
#define STR_IN 							"In"
#define STR_THE	 						"The"
#define STR_OPERATION					"Operation"
#define STR_ZERO						"Zero"
#define STR_DATA						"Data"
#define STR_LENGTH						"Length"
#define STR_BUSY						"Busy"
#define STR_TIMEOUT						"Timeout"
#define STR_OCCURRED					"Occurred"
#define STR_WRONG						"Wrong"
#define STR_IP							"IP"
#define STR_TCP							"TCP"
#define STR_SN							"SN"
#define STR_GW							"GW"
#define STR_MAC							"MAC"
#define STR_PORT						"Port"
#define STR_ADDRESS						"Address"
#define STR_CONNECTION					"Connection"
#define STR_UNKNOWN 					"Unknown"
#define STR_VALUE 						"Value"
#define STR_EEPROM	 					"EEPROM"
#define STR_ERASING 					"Erasing"
#define STR_READING	 					"Reading"
#define STR_READ	 					"Read"
#define STR_WRITING	 					"Writing"
#define STR_WRITE	 					"Write"
#define STR_SERIAL	 					"Serial"
#define STR_SEND						"Send"
#define STR_MB		 					"MB"
#define STR_REQ 						"REQ"
#define STR_RESP 						"RESP"
#define STR_BYTE 						"Byte"
#define STR_DEV 						"Dev"
#define STR_PARITY		 				"Parity"
#define STR_FRAME		 				"Frame"
#define STR_NOISE		 				"Noise"
#define STR_OVERRUN		 				"Overrun"
#define STR_DMA	 						"DMA"
#define STR_TX	 						"TX"
#define STR_RTU	 						"RTU"
#define STR_I2C	 						"I2C"
#define STR_COMM	 						"Comm"

#define STR_FORMATE_IP					"%d.%d.%d.%d"
#define STR_FORMATE_MAC					"%12X"

#endif /* INC_STRINGS_H_ */
